export const Tasks = [
  {
    id: 1,
    title: "Task1",
    priority: 0,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Pending",
  },
  {
    id: 2,
    title: "Task2",
    priority: 1,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "In-Progress",
  },
  {
    id: 3,
    title: "Task3",
    priority: 2,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Completed",
  },
  {
    id: 4,
    title: "Task4",
    priority: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Delivered",
  },
  {
    id: 5,
    title: "Task5",
    priority: 4,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Deployed",
  },
  {
    id: 6,
    title: "Task6",
    priority: 5,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Delivered",
  },
  {
    id: 7,
    title: "Task7",
    priority: 6,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Deployed",
  },
  {
    id: 8,
    title: "Task8",
    priority: 7,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Delivered",
  },
  {
    id: 9,
    title: "Task8",
    priority: 7,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Delivered",
  },
  {
    id: 10,
    title: "Task8",
    priority: 7,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    assignTo: "John Doe",
    status: "Delivered",
  },
];
